import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ApolloProvider } from '../providers/ApolloProvider'

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} font-pretendard`}>
        <ApolloProvider>
          <div className="layout">{children}</div>
        </ApolloProvider>
      </body>
    </html>
  )
}
